/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdev_libjam_mt_TouchHandler */

#ifndef _Included_com_asdev_libjam_mt_TouchHandler
#define _Included_com_asdev_libjam_mt_TouchHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdev_libjam_mt_TouchHandler
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_asdev_libjam_mt_TouchHandler_init
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
